# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterinfo',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
