# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190810_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterinfo',
            name='aadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voterinfo',
            name='voterid',
            field=models.IntegerField(),
        ),
    ]
