# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20190811_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterinfo',
            name='contractid',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
