# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_voterinfo_contractid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterinfo',
            name='is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
