# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_voterinfo_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterinfo',
            name='contractid',
            field=models.IntegerField(default=0),
        ),
    ]
