# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20190817_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterinfo',
            name='constituency_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voterinfo',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
