# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-20 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20190820_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterinfo',
            old_name='constituency_id',
            new_name='constituency',
        ),
    ]
